-- 문제: 입양 시각 구하기(1)
-- https://school.programmers.co.kr/learn/courses/30/lessons/59412

SELECT 
HOUR(DATETIME) AS HOUR,
COUNT(*) 'COUNT'
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR
ORDER BY HOUR ASC;

/*
SELECT HOUR(DATETIME) AS HOUR,
       COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR BETWEEN 9 AND 19
ORDER BY HOUR;
*/
